# Generated by Django 4.1.5 on 2023-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Movie_name', models.CharField(max_length=50)),
                ('Actress_name', models.CharField(max_length=50)),
                ('Actor_name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
