# Generated by Django 4.1.5 on 2023-03-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='date',
            new_name='date_in_MM_DD_YY',
        ),
    ]
